version: "3.9"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: build
    volumes:
      - ./docker-compose.yml:/app/docker-compose2.yml
      - ./test-volumes:/app/test-volumes2
