version: "3.9"
services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./docker-compose.yml
        target: /src/docker-compose2.yml
    ports:
     - "8079:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
