version: "3.9"
services:
  web:
    volumes:
      - ./logs:./logs
      - ./docker-compose.yml:./docker-compose2.yml
    image: nginx
    ports:
     - "8079:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
