version: "1.0"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    pull_policy: build
    volumes:
      - ${PWD}/docker-compose.yml:/app/docker-compose2.yml
      - ${PWD}/test-volumes:/app/test-volumes2
    # ports:
    #  - "8079:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
